name: Teste Vivo
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Executar Cypress
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js

      - name: Salvar artefatos de teste
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos